apiVersion: apps/v1
kind: Deployment
metadata:
  name: dadjokes-deployment
  labels:
    app: dadjokes
spec:
  replicas: 3
  revisionHistoryLimit: 3            # keep a few old ReplicaSets for rollback
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1              # ensure at least N-1 pods available during updates
      maxSurge: 1
  selector:
    matchLabels:
      app: dadjokes
  template:
    metadata:
      labels:
        app: dadjokes
    spec:
      containers:
        - name: dadjokes
          # Use a single canonical image name. If you keep CI as 'maxlieb/dadjokes-api', use that here:
          image: maxlieb/dadjokes-api:latest   # or pin to a SHA tag from CI for immutability
          imagePullPolicy: Always               # ensure pulling latest tag on each rollout
          ports:
            - containerPort: 5000
          env:
            - name: JOKE_LIMIT
              value: "20"
            - name: NTFY_TOPIC
              value: "dadjokes-max-bido19-midproj"
            - name: MAX_RECORDS
              value: "30"
            - name: NTFY_BASE
              value: "https://ntfy.sh"
            # - name: NTFY_AUTH
            #   valueFrom:
            #     secretKeyRef:
            #       name: ntfy-secret
            #       key: token
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
      restartPolicy: Always
