apiVersion: v1
kind: Service
metadata:
  name: dadjokes-service
spec:
  type: LoadBalancer
  selector:
    app: dadjokes
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  # For external access on Minikube: uncomment and run `minikube tunnel`
  # type: LoadBalancer
